version: '3.8'

services:
  postgres:
    image: library/postgres:12.7-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: tdb
      POSTGRES_USER: system_user
      POSTGRES_PASSWORD: postgres
      PDGATA: /var/lib/postgres/data
    volumes:
      - localsystem_postgres:/var/lib/postgres/data:rw
    ports:
      - "5432:5432"

  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      target: app_php
    image: local_system/php:dev
    restart: on-failure
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    depends_on:
      - postgres
    volumes:
      - .:/app:rw,cached
      - localsystem_var:/app/var
#      - localsystem_var:/app/var:rw
#      - localsystem_vendor:/app/vendor:rw

  nginx:
    build:
      context: .
      target: app_nginx
    image: local_system/nginx:dev
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
    - ./public:/app/public:ro
    depends_on:
      - php

volumes:
  localsystem_postgres:
  localsystem_var: